<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20160607125833 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('ALTER TABLE sandstorm_usermanagement_domain_model_registrationflow CHANGE firstname firstname VARCHAR(255) NOT NULL, CHANGE lastname lastname VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE sandstorm_usermanagement_domain_model_user DROP companyname, DROP resetpasswordtoken, DROP activationtoken, DROP activationtokenvaliduntil, DROP resetpasswordtokenvaliduntil, DROP newactivationtokenrequested');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('ALTER TABLE sandstorm_usermanagement_domain_model_registrationflow CHANGE firstname firstname VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE lastname lastname VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE sandstorm_usermanagement_domain_model_user ADD companyname VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, ADD resetpasswordtoken VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, ADD activationtoken VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, ADD activationtokenvaliduntil DATETIME DEFAULT NULL, ADD resetpasswordtokenvaliduntil DATETIME DEFAULT NULL, ADD newactivationtokenrequested TINYINT(1) DEFAULT NULL');
    }
}
